### ISSUE TITLE
Mod Labeled as compatible with 1.19.3 But is not

### ISSUE THREAD

**Issue by boshyXD32** [Daxanius/NoMiningCooldown#1]
supposedly the mod is compatible with 1.19.3 acording to the modrinth description but when trying to launch 1.19.3 it says is only compatible with 1.19: 
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'No Mining Cooldown' (nmc) 1.0 with any version that is compatible with:
		 - minecraft 1.19.3
Unmet dependency listing:
	 - Mod 'No Mining Cooldown' (nmc) 1.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.3!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Daxanius** [comment]
Must've been an oversight on my part; I'm gonna fix it right away. I apologize for the inconvenience.

**Comment by Daxanius** [comment]
The issue has been addressed in the 1.1 release which can be found [here](https://modrinth.com/mod/no-mining-cooldown/version/1.1)
