### ISSUE TITLE
Does not work on version 1.21.3.

### ISSUE THREAD

**Issue by Timokaproka** [Daxanius/NoMiningCooldown#7]
When using the hotkey, the game crashes. [Crash log](https://mclo.gs/XmX7vpg) 
Version: Fabric-1.21.3

**Comment by Muffinmaker2** [comment]
it seems to invoke this method method_43496(net.minecraft.class_2561 but this doesnt exist in 1.21.3?

**Comment by meowinqq** [comment]
facing the same issue, except the game softlocks on the loading screen as it gets caught in a resource reload :')

**Comment by Daxanius** [comment]
This has officially been fixed on the 2.4 release
